print("hola soy JUAN GALLEGO EL COMMITTER")
print("Soy Deisy Ruiz Desarrolladora Frontend")
print("Hola  soy Kevin y soy un desarollador JR")
print("Hola soy Alejo desarrollador junior")
print("Hola, soy Jenn y soy developer junior")
